name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: 
        type: choice
        options:
          - alerts_frame_windows_test
          - elements_test
          - form_test
          - interactions_test
          - widgests_test

jobs:   
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: alerts_frame_windows_test
        if: "github.event.inputs.deployment_target == 'alerts_frame_windows_test'"
        run: pytest tests/alerts_frame_windows_test.py::TestAlertsFrameWindow
      - name: elements_test
        if: "github.event.inputs.deployment_target == 'elements_test'"
        run: pytest tests/elements_test.py::TestElements
      - name: form_test
        if: "github.event.inputs.deployment_target == 'form_test'"
        run: pytest tests/form_test.py::TestForm
      - name: interactions_test
        if: "github.event.inputs.deployment_target == 'interactions_test'"
        run: pytest tests/interactions_test.py::TestInteractions
      - name: widgests_test
        if: "github.event.inputs.deployment_target == 'widgests_test'"
        run: pytest tests/widgests_test.py::TestWidgets


     